#! /bin/bash
rm -f .error$$
ERROR=0
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" LANG=C
(make V=1 $@ 2>&1 || touch .error$$)| ../extras/package/win32/../../../extras/buildsystem/make.pl
test -f .error$$ && ERROR=1
rm -f .error$$
exit $ERROR
